CREATE TABLE MEMBER
AS
	SELECT EMAIL userid, EMAIL passowrd, LOWER(EMAIL) || '@galapagos.org' email
	FROM HR.EMPLOYEES;
	
SELECT * FROM MEMBER;

CREATE TABLE EMP_ALTER
AS SELECT * FROM EMP;

SELECT * FROM EMP_ALTER;

ALTER TABLE EMP_alter
ADD hp varchar2(20);

SELECT * FROM EMP_ALTER;

ALTER TABLE EMP_ALTER
RENAME COLUMN hp TO tel;

SELECT  * FROM emp_alter;

ALTER TABLE EMP_ALTER 
MODIFY empno number(5);

SELECT  * FROM emp_alter;

ALTER TABLE EMP_ALTER
DROP COLUMN TEL;

SELECT * FROM EMP_ALTER;

RENAME EMP_ALTER TO EMP_RENAME;

SELECT * FROM EMP_RENAME;

TRUNCATE TABLE EMP_RENAME;

SELECT * FROM EMP_RENAME;